# Generated by Django 3.2.16 on 2023-01-02 17:32

import contact.file_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[contact.file_size.file_size]),
        ),
    ]
