# Generated by Django 3.2.16 on 2022-11-26 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1)),
                ('seating_amount', models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (6, '6'), (8, '8'), (9, '9'), (10, '10'), (12, '12'), (15, '15')], default=2)),
                ('disabled_friendly', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('guest_amount', models.IntegerField(default=2)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(0, '11:15AM - 12:00PM'), (1, '12:15PM - 1:45PM'), (2, '1:15PM - 3:45PM'), (3, '2:15PM - 4:45PM'), (4, '3:15PM - 5:45PM'), (5, '4:15PM - 6:45PM'), (6, '5:15PM - 7:45PM'), (7, '6:15PM - 9:00PM'), (8, '7:15PM - 9:45PM')], default=1)),
                ('booked_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_table', to='reservations.table')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
