# Generated by Django 3.2.16 on 2022-11-28 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20221128_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_amount',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
