# Generated by Django 3.2.16 on 2022-11-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20221120_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='allergens',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.allergen'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
