# Generated by Django 3.2.16 on 2022-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20221120_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='allergens',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Allergen'),
        ),
    ]
