# Generated by Django 3.2.16 on 2022-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20221120_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='menu.Allergen'),
        ),
    ]
